### ISSUE TITLE
Volume widget not working

### ISSUE THREAD

**Issue by T3KKAN** [streetturtle/awesome-wm-widgets#251]
I followed the readme instructions. I have pacmd, amixer, the "arc" icon pack and an acordingly modified rc.lua. Awesome wm gave me no error but the widget isn't appearing in the bar. I decided to install the battery widget and that one works.

**Comment by streetturtle** [comment]
Can you please verify that you're using the latest master. There was some issue which has been fixed recently.

**Comment by T3KKAN** [comment]
Even though I was already using the latest master i downloaded it again today and the problem still persists.

**Comment by streetturtle** [comment]
Can you please paste how you define the widget

**Comment by T3KKAN** [comment]
Yes, thank you. 

-- Battery widget
local battery_widget = require("awesome-wm-widgets.battery-widget.battery")
-- Volume widget
local volume_widget = require('awesome-wm-widgets.volume-widget.volume')

...

    -- Add widgets to the wibox
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            mylauncher,
            s.mytaglist,
            s.mypromptbox,
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            battery_widget(),
            -- default
            volume_widget(),
            -- customized
            volume_widget{
                    type = 'horizontal_barc'
            },
            mykeyboardlayout,
            wibox.widget.systray(),
            mytextclock,
            s.mylayoutbox,
        },
    }

**Comment by murchu27** [comment]
Just chiming in to say that I'm having the same problem with the volume widget, but battery widget is working. Defined like so:

```
local battery_widget = require("awesome-wm-widgets.battery-widget.battery")
local volume_widget = require("awesome-wm-widgets.volume-widget.volume")

...

s.mywibox:setup {
    layout = wibox.layout.align.horizontal,
    { -- Left widgets
        layout = wibox.layout.fixed.horizontal,
        mylauncher,
        s.mytaglist,
        s.mypromptbox,
        separator,
    },
    s.mytasklist, -- Middle widget
    { -- Right widgets
        layout = wibox.layout.fixed.horizontal,
        mykeyboardlayout,
        volume_widget(),
        battery_widget({warning_msg_title = "Get ya charga"}),
        wibox.widget.systray(),
        separator,
        mytextclock,
        s.mylayoutbox,
    },
}
```

**Comment by streetturtle** [comment]
Unfortunately I cannot reproduce it, but I think the problem could be in amixer. The widget runs following command, and expects to have corresponding output:

```bash
$ amixer -D pulse sget Master
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 19658 [30%] [on]
  Front Right: Playback 19658 [30%] [on]
```

Could you please paste the output of that command?

**Comment by T3KKAN** [comment]
You are right. This is the output: 

> ALSA lib control.c:1471:(snd_ctl_open_noupdate) Invalid CTL pulse
> amixer: Mixer attach pulse error: No such file or directory

Could you please tell how to fix it?

**Comment by T3KKAN** [comment]
I tried the same command without  "-D pulse" and i get the expected output.

```
$ amixer sget Master
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 60 [69%] [-20.25dB] [on]
```

**Comment by T3KKAN** [comment]
I found a fix, atleast for me.
I went on /awesome-wm-widgets/volume-widget/volume.lua and changed the previous 4 lines to this:

> local GET_VOLUME_CMD = 'amixer sget Master'
> local INC_VOLUME_CMD = 'amixer sset Master 5%+'
> local DEC_VOLUME_CMD = 'amixer sset Master 5%-'
> local TOG_VOLUME_CMD = 'amixer sset Master toggle'

Everything was working except i couldn't unmute after muting, so i installed: "pulseaudio-alsa" and it's working perfectly now.

The only problem i'm having now is that i cannot change the default volume icon to any other, even when using:

> volume_widget{
>                 type = 'arc'
>         },

**Comment by romildo** [comment]
> You are right. This is the output:
> 
> > ALSA lib control.c:1471:(snd_ctl_open_noupdate) Invalid CTL pulse
> > amixer: Mixer attach pulse error: No such file or directory
> 
> Could you please tell how to fix it?

I am getting this same result on my system.

**Comment by murchu27** [comment]
I installed `pulseaudio-alsa` like @T3KKAN, and that fixed the problem for me immediately, without needing to change the commands or anything. Good find!

**Comment by streetturtle** [comment]
> I found a fix, atleast for me.
> I went on /awesome-wm-widgets/volume-widget/volume.lua and changed the previous 4 lines to this:
> 
> > local GET_VOLUME_CMD = 'amixer sget Master'
> > local INC_VOLUME_CMD = 'amixer sset Master 5%+'
> > local DEC_VOLUME_CMD = 'amixer sset Master 5%-'
> > local TOG_VOLUME_CMD = 'amixer sset Master toggle'
> 
> Everything was working except i couldn't unmute after muting, so i installed: "pulseaudio-alsa" and it's working perfectly now.
> 
> The only problem i'm having now is that i cannot change the default volume icon to any other, even when using:
> 
> > volume_widget{
> > type = 'arc'
> > },

@T3KKAN for the moment it's not possible. Could you please create another issue for this.

**Comment by vuki656** [comment]
Not sure if it related but my widget also stopped working and after looking into the source I noticed you were using `pavucontrol`, so I installed it and it worked. 

Also, `amixer -D pulse sget Master` output was as expected, but it wasn't working. 

```
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 36043 [55%] [on]
  Front Right: Playback 36043 [55%] [on]
```
